tasks:
  - name: Install RStudio
    init: |
      sudo apt-get update
      sudo apt-get upgrade -y
      sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9
      sudo add-apt-repository 'deb https://cloud.r-project.org/bin/linux/ubuntu focal-cran40/'
      sudo apt install -y r-base r-base-core r-recommended r-base-dev gdebi-core build-essential libcurl4-gnutls-dev libxml2-dev libssl-dev
      wget https://rstudio.org/download/latest/stable/server/bionic/rstudio-server-latest-amd64.deb
      gp ports visibility 8787:public
      sudo gdebi --n rstudio-server-latest-amd64.deb
      sudo rstudio-server start
      echo "********************************************"
      echo "Now you have to complete the creation of a new user: type a password, confirm it, accept the other defaults and complete the user. Then login to the RStudio Server using this new user and their password "
      sudo adduser hank
  - name: Open README 
    command: gp open README.md
  - name: Open RStudio Tab
    command: gp preview $(gp url 8787) --external
ports:
  # RStudio port
  - port: 8787
    onOpen: notify
    visibility: public    
